version: 2.1
setup: true
orbs:
  path-filtering: circleci/path-filtering@2.0.1
workflows:
  setup:
    jobs:
      - path-filtering/filter:
          base-revision: main
          mapping: |
            infra/aws/lambda/endpoint/pre_signup_trigger lambda-pre-signup-trigger true
          config-path: .circleci/lambda_workflows.yml
      