name: Deploy changed Lambda endpoints

on:
  workflow_dispatch:

jobs:
  discover-lambdas:
    runs-on: ubuntu-latest
    outputs:
      folders: ${{ steps.set-folders.outputs.folders }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Get changed folders
        id: set-folders
        run: |
          # Get list of changed files in the folder
          CHANGED_FILES=$(find infra/aws/lambda/endpoint -mindepth 1 -maxdepth 1 -type d -exec basename {} \; | sort | uniq)
          # Extract unique folders (one level below endpoint)
          FOLDERS=$(echo "$CHANGED_FILES" | jq -R -s -c 'split("\n")[:-1]')
          echo "Changed folders: $FOLDERS"
          echo "folders=$FOLDERS" >> $GITHUB_OUTPUT

  build-and-deploy-lambda:
    needs: discover-lambdas
    if: ${{ needs.discover-lambdas.outputs.folders != '[]' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder: ${{ fromJson(needs.discover-lambdas.outputs.folders) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy Lambda for ${{ matrix.folder }}
        run: |
          echo "Deploying Lambda in infra/aws/lambda/endpoint/${{ matrix.folder }}"

      - name: Build go artifact
        run: |
          # Verify the folder exists
          if [ ! -d "infra/aws/lambda/endpoint/${{ matrix.folder }}" ]; then
            echo "Directory infra/aws/lambda/endpoint/${{ matrix.folder }} does not exist"
            exit 1
          fi
          # Change to the directory and build the Go artifact
          echo "Building Go artifact in infra/aws/lambda/endpoint/${{ matrix.folder }}"
          cd infra/aws/lambda/endpoint/${{ matrix.folder }}
          # Install Go dependencies
          go mod tidy

          # Build the Go binary
          go build -o main ./...

      - name: Package Lambda function
        run: |
          echo "Packaging Lambda function in infra/aws/lambda/endpoint/${{ matrix.folder }}"
          cd infra/aws/lambda/endpoint/${{ matrix.folder }}
          zip -r lambda.zip main
