name: Deploy changed Lambda endpoints

on:
  push:
    branches:
      - main
    paths:
      - 'infra/aws/lambda/endpoint/**'
    

jobs:
  discover-lambdas:
    runs-on: ubuntu-latest
    outputs:
      folders: ${{ steps.set-folders.outputs.folders }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Get changed folders
        id: set-folders
        run: |
          # Get list of changed files in the folder. Currently, there are a few lambda endpoints so we will discover all of them.
          CHANGED_FILES=$(find infra/aws/lambda/endpoint -mindepth 1 -maxdepth 1 -type d -exec basename {} \; | sort | uniq)
          # Extract unique folders (one level below endpoint)
          FOLDERS=$(echo "$CHANGED_FILES" | jq -R -s -c 'split("\n")[:-1]')
          echo "Changed folders: $FOLDERS"
          echo "folders=$FOLDERS" >> $GITHUB_OUTPUT
  
  # Build lambda images
  build-lambdas:
    needs: discover-lambdas
    if: ${{ needs.discover-lambdas.outputs.folders != '[]' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder: ${{ fromJson(needs.discover-lambdas.outputs.folders) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ matrix.folder }}
          restore-keys: |
            ${{ runner.os }}-buildx-${{ matrix.folder }}

      - name: Build Lambda for ${{ matrix.folder }}
        run: |
          echo "Building Lambda in infra/aws/lambda/endpoint/${{ matrix.folder }}"
      
      - name: Build Docker image
        run: |
          cd infra/aws/lambda
          docker buildx build \
          --build-arg LAMBDA_TASK=${{ matrix.folder }} \
          --cache-from type=local,src=/tmp/.buildx-cache \
          --cache-to type=local,dest=/tmp/.buildx-cache \
          --load \
          -t ${{ matrix.folder }}:${{ github.sha }} .
    

      - name: Save Docker image as artifact
        run: |
          docker save ${{ matrix.folder }}:${{ github.sha }} -o /tmp/${{ matrix.folder }}-${{ github.sha }}.tar
      
      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.folder }}-${{ github.sha }}
          path: /tmp/${{ matrix.folder }}-${{ github.sha }}.tar

  deploy-lambdas:
    needs: 
      - build-lambdas
      - discover-lambdas
    if: ${{ needs.discover-lambdas.outputs.folders != '[]' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder: ${{ fromJson(needs.discover-lambdas.outputs.folders) }}
    steps:
      - name: Download Docker image artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.folder }}-${{ github.sha }}
          path: /tmp

      - name: Load Docker image
        run: |
          docker load -i /tmp/${{ matrix.folder }}-${{ github.sha }}.tar

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_DOCKER_BUILD_ROLE_ARN }}
          aws-region: ap-southeast-1 # Default region for ECR

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Tag image for ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: expense-tracking
        run: |
          echo "Tagging image for ECR repository: $ECR_REPOSITORY:${{ matrix.folder }}-${{ github.sha }}"
          docker tag ${{ matrix.folder }}:${{ github.sha }} $ECR_REGISTRY/$ECR_REPOSITORY:${{ matrix.folder }}-${{ github.sha }}

      - name: Push image to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: expense-tracking
        run: |
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:${{ matrix.folder }}-${{ github.sha }}


